---
title: "Demonstration of network attacks with Scapy: scattack, a single platform to launch several attacks"
author:
    - name: Sayafdine Said
      email: sayafdine.said@outlook.com
      affiliations:
        - ref: sorb
    - name: Aris Berkane
      email: aris.berkane@etu.sorbonne-universite.fr
      affiliations:
        - ref: sorb
    - name: Mohammed Benaissa
      email: mohammed.benaissa@etu.sorbonne-universite.fr
      affiliations:
        - ref: sorb
    - name: Serigne Saliou Ndiaye
      email: serigne.saliou.ndiaye@etu.sorbonne-universite.fr
      affiliations:
        - ref: sorb
affiliations:
  - id: sorb
    name: Sorbonne Université
abstract: >
    We present the development of a tool to launch network attacks using the Scapy library,
    to demonstrate the use of the library in various scenarios.
    Implemented network attacks include Wi-Fi deauthentication, ARP cache poisoning and DHCP starvation.
    Are described the usage of the library and its main features, the implementation of the tool and the
    attacks, and the results of the tests performed.
    The tool is available at https://github.com/musikid/scattack.
bibliography: report.bib
---

<!--
  Introduction
    - Context
    - Scapy
    - Attacks
      - Wifi deauthentication
      - ARP cache poisoning
      - DHCP Starvation
    - Project
      - scapy
      - gui
  Project
    - Implementation
    - Usage
    - Results
  Conclusion
    - Recap
    - Future work
-->

# Introduction

Network attacks are a major concern in our world growingly connected.
As evidenced by the attacks of SolarWinds (@SolarWinds),
which involved the compromise of the SolarWinds Orion platform
through a stolen virtual private network (VPN) account,
or GitHub (@GitHubDDoS) DDoS attack, relying on the use of a memcached amplification attack,
the nature of network assaults is as diverse as their consequences.

To defend from such breaches, it is necessary to understand
and be able to reproduce those attacks in a controlled environment.
Depending on their nature, implementating them require different tools and techniques,
from network sniffing to packet crafting.

In this context, the Scapy library is a powerful tool to perform network analysis and penetration testing.

## Scapy

Scapy is a powerful packet manipulation library for Python,
which allows to forge or decode packets of a wide number of protocols,
send them on the wire, capture them, match requests and replies,
and much more.
It has been written by Philippe Biondi and the Scapy community in 2003,
as a way to perform network analysis and penetration testing in a simple and efficient way,
without the need to write complex scripts or programs.
It features a simple and extensive API, is able to run on a fairly wide range of platforms,
and is open-source, which makes it a very attractive tool for
Its ability to craft packets on the fly for a wide range of protocols makes it a very versatile tool.
Our goal is to demonstrate the usage of these features to perform several network attacks,
in particular Wi-Fi deauthentication, ARP cache poisoning and DHCP starvation attacks.

## Project

The project consists in the development of a single platform tool
to launch several network attacks using the Scapy library,
namely Wi-Fi deauthentication, ARP cache poisoning and DHCP starvation attacks.
The attacks differ in their nature and implementation,
enabling to better assess the capabilities of the library in multiple scenarios.


In this report, we present the development of a tool to launch network attacks using the Scapy library,
to demonstrate the use of the library to perform different network attacks,
in particular Wi-Fi deauthentication, ARP cache poisoning and DHCP starvation attacks.
